# https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-in-docker-executor

image: docker:latest

# When using dind (docker-in-docker), it's wise to use the overlayfs driver for improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

build:
  stage: build
  script:
    - make IMAGE=${CI_REGISTRY_IMAGE} TAG_DEVEL=${CI_COMMIT_REF_NAME} build push-devel

test001:
  stage: test
  script:
    - make IMAGE=${CI_REGISTRY_IMAGE} TAG_DEVEL=${CI_COMMIT_REF_NAME} pull-devel test001

release-image:
  stage: release
  script:
    - make IMAGE=${CI_REGISTRY_IMAGE} TAG_DEVEL=${CI_COMMIT_REF_NAME} pull-devel tag-latest push-latest
  only:
    - master

deploy:
  stage: deploy
  script:
    - make IMAGE=${CI_REGISTRY_IMAGE} TAG_DEVEL=${CI_COMMIT_REF_NAME} deploy
  only:
    - master
