# https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-in-docker-executor

image: docker:latest

# When using dind (docker-in-docker), it's wise to use the overlayfs driver for improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

variables:
  IMAGE_TAG_COMMIT: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  IMAGE_TAG_LATEST: ${CI_REGISTRY_IMAGE}:latest

before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

build:
  stage: build
  script:
    - docker build --pull -t ${IMAGE_TAG_COMMIT} .
    - docker push ${IMAGE_TAG_COMMIT}

test001:
  stage: test
  script:
    - docker pull ${IMAGE_TAG_COMMIT}
    - docker run ${IMAGE_TAG_COMMIT} /usr/local/bin/tarzan-test-001

release-image:
  stage: release
  script:
    - docker pull ${IMAGE_TAG_COMMIT}
    - docker tag ${IMAGE_TAG_COMMIT} ${IMAGE_TAG_LATEST}
    - docker push ${IMAGE_TAG_LATEST}
  only:
    - master

deploy:
  stage: deploy
  script:
    - make deploy
  only:
    - master
