version: '3.3'
services:

  zeppelin:
    image: registry.gitlab.com/rychly-edu/docker/docker-zeppelin
    environment:
      - PROP_ZEPPELIN_zeppelin_server_addr=0.0.0.0
      - ZEPPELIN_PORT=8080
      - ZEPPELIN_NOTEBOOK_DIR=/home/zeppelin
      - MASTER=local[*]
      - PROP_SPARK_spark_jars=/opt/michal-beder-tarzan/Java/ndx-spark-shell/target
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/notebook:/home/zeppelin
      - ./components/michal-beder-tarzan:/opt/michal-beder-tarzan
    deploy:
      placement:
        constraints: [node.role == manager]
