version: '3.3'
services:

  zeppelin:
    image: registry.gitlab.com/rychly-docker/docker-zeppelin
    environment:
      - ZEPPELIN_PORT=8080
      - ZEPPELIN_NOTEBOOK_DIR=/home/zeppelin
      - MASTER=local[*]
      - PROP_SPARK_spark_jars=/opt/rysavy-ondrej-tarzan/Java/ndx-spark-shell/target
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/notebook:/home/zeppelin
      - ./components/rysavy-ondrej-tarzan:/opt/rysavy-ondrej-tarzan
    deploy:
      placement:
        constraints: [node.role == manager]
