version: '3'
services:
  builder:
    image: maven:3-jdk-8-alpine
    entrypoint:
      - /usr/local/bin/mvn-entrypoint.sh
      - sh
      - -c
      - apk --no-cache add attr && setfattr -n user.pax.flags -v em /usr/bin/java /usr/lib/jvm/*/bin/java && cd /usr/src/mymaven/Java && exec mvn clean package
    volumes:
      - ./michal-beder-tarzan:/usr/src/mymaven
