version: '3'
services:
  builder:
    image: maven:3-jdk-8-alpine
    entrypoint:
      - /usr/local/bin/mvn-entrypoint.sh
      - sh
      - -c
      - cd /usr/src/mymaven/Java && exec mvn clean package
    volumes:
      - ./rysavy-ondrej-tarzan:/usr/src/mymaven
